
logging.level.alex.msu.gradwork=debug

#spring.datasource.url=jdbc:h2:file:~/data/demo
##spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.database-platform=alex.msu.gradwork.dialect.SQLDialect

spring.datasource.url=jdbc:sqlite:sqlitesample.db
spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.jpa.hibernate.ddl-auto = none
spring.jpa.hibernate.ddl-auto = update
#server.error.include-stacktrace=never

#spring.datasource.url=jdbc:h2:file:./data/fileDb

spring.datasource.username=
spring.datasource.password=