logging.level.alex.msu.gradwork=debug



#h2 db

spring.datasource.url=jdbc:h2:file:./data/fileDb
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#sqlite db

#spring.jpa.database-platform=alex.msu.gradwork.dialect.SQLDialect
#spring.datasource.url=jdbc:sqlite:sqlitesample.db;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.sqlite.JDBC



spring.jpa.hibernate.ddl-auto = create-drop

spring.datasource.username=sa
spring.datasource.password=

spring.application.name=springboot-thymeleaf-pagination-and-sorting